name: ci

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - 'README.md'
      - 'README_zh_CN.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - 'README.md'
      - 'README_zh_CN.md'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
    
      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y make gcc upx-ucl

      - name: Build all
        run: |
          make
